In [1]:
include("../src/Dyn3d.jl")
using Dyn3d
using Base.Test
using Plots
gr()

Plots.GRBackend()

In [2]:
include("../src/config_files/2dThrow.jl")

Config info set up.


In [3]:
# add bodys
bodys = Vector{SingleBody}(nbody) # body system
for i = 1:nbody
    bodys[i] = AddBody(i, config_body) # add body
end



4-element Array{Dyn3d.ConstructSystem.SingleBody,1}:
 body_id = 1, parent_id = 0, nchild = 0, chid = Int64[], nverts = 4
q = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
v = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
v̇ = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

 body_id = 2, parent_id = 0, nchild = 0, chid = Int64[], nverts = 4
q = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
v = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
v̇ = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

 body_id = 3, parent_id = 0, nchild = 0, chid = Int64[], nverts = 4
q = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
v = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
v̇ = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

 body_id = 4, parent_id = 0, nchild = 0, chid = Int64[], nverts = 4
q = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
v = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
v̇ = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]


In [4]:
# add joints
joints = Vector{SingleJoint}(njoint) # joint system
for i = 1:njoint
    joints[i] = AddJoint(i, config_joints[i]) # add joint
end

joints

4-element Array{Dyn3d.ConstructSystem.SingleJoint,1}:
 joint_id = 1, joint_type = revolute, body1 = 0
nudof = 1, ncdof = 5, np = 0, na = 1
udof = [3], cdof = [1, 2, 4, 5, 6]
udof_p = Int64[], udof_a = [3]
nudof_HERK = 0, ncdof_HERK = 6
udof_HERK = Int64[], cdof_HERK = [1, 2, 3, 4, 5, 6]
qJ = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
vJ = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
v̇J = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

 joint_id = 2, joint_type = planar, body1 = 1
nudof = 3, ncdof = 3, np = 2, na = 1
udof = [3, 4, 5], cdof = [1, 2, 6]
udof_p = [3, 4], udof_a = [5]
nudof_HERK = 2, ncdof_HERK = 4
udof_HERK = [3, 4], cdof_HERK = [1, 2, 5, 6]
qJ = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
vJ = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
v̇J = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
          
 joint_id = 3, joint_type = planar, body1 = 2
nudof = 3, ncdof = 3, np = 2, na = 1
udof = [3, 4, 5], cdof = [1, 2, 6]
udof_p = [3, 4], udof_a = [5]
nudof_HERK = 2, ncdof_HERK = 4
udof_HERK = [3, 4], cdof_HERK = [1, 2, 5, 6]
qJ = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0

In [5]:
# assemble system to a chain
system = System(ndim, nbody, njoint, gravity, num_params)
bodys, joints, system = AssembleSystem!(bodys, joints, system)

system

ndim = 2, njoint = 4, nbody = 4
ndof = 24, nudof = 10, ncdof = 14, np = 6, na = 4
udof = [3, 9, 10, 11, 15, 16, 17, 21, 22, 23]
udof_p = [9, 10, 15, 16, 21, 22]
udof_a = [3, 11, 17, 23]
nudof_HERK = 6, ncdof_HERK = 18
udof_HERK = [9, 10, 15, 16, 21, 22]
gravity = [0.0, 0.0, 0.0]
kinmap = [1 1; 2 3; 3 3; 4 3]


In [8]:
bodys

4-element Array{Dyn3d.ConstructSystem.SingleBody,1}:
 body_id = 1, parent_id = 0, nchild = 1, chid = [2], nverts = 4
q = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
v = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
v̇ = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    
 body_id = 2, parent_id = 1, nchild = 1, chid = [3], nverts = 4
q = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
v = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
v̇ = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    
 body_id = 3, parent_id = 2, nchild = 1, chid = [4], nverts = 4
q = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
v = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
v̇ = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    
 body_id = 4, parent_id = 3, nchild = 0, chid = Int64[], nverts = 4
q = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
v = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
v̇ = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]


In [6]:
a = 4.0
tᵣ = [π/2, π, 3π/2, 2π]

t = linspace(-1, 10, 200)

f(t) = cosh(a*(t-tᵣ[1]))
g(t) = cosh(a*(t-tᵣ[2]))
m(t) = cosh(a*(t-tᵣ[3]))
n(t) = cosh(a*(t-tᵣ[4]))

ḟ(t) = a*sinh(a*(t-tᵣ[1]))
ġ(t) = a*sinh(a*(t-tᵣ[2]))
ṁ(t) = a*sinh(a*(t-tᵣ[3]))
ṅ(t) = a*sinh(a*(t-tᵣ[4]))

func(t) = log(f(t)*n(t)/(g(t)*m(t)))
ddt_func(t) = g(t)*m(t)/(f(t)*n(t))*
              (-f(t)*n(t)*(ġ(t)*m(t)+ṁ(t)*g(t))/(g(t).^2*m(t).^2)
                  + (ḟ(t)*n(t)+ṅ(t)*f(t))/(g(t)*m(t)))


scatter(tᵣ,zeros(4))
plot!(t,[func,ddt_func])

print(func(π),ddt_func(π))

11.8732234338113883.9999442028141754

In [7]:
a = 1.0
t = linspace(-1, 10, 200)

f(t) = 0.5*(tanh(a*t) + 1)
dfdt(t) = 0.5*a*sech(a*t).^2

plot(t,[f,dfdt])
print(f(π/2),dfdt(π/2))

0.95857616783363720.07941579659003167